server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userservice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka
      
      
serviceVersion: 2.0
